version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000/ws
    depends_on:
      - backend
    networks:
      - codewise-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
      - DEFAULT_PROVIDER_MODEL=${DEFAULT_PROVIDER_MODEL}
      - PRIMARY_PROVIDER=cerebras
      - MCP_SERVER_URL=http://mcp_server:8001
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    depends_on:
      - mcp_server
    volumes:
      - ./workspace:/workspace
      - ./backend:/app/backend
    networks:
      - codewise-network

  mcp_server:
    build: ./mcp_server
    environment:
      - WORKSPACE_DIR=/workspace
    volumes:
      - ./workspace:/workspace
    networks:
      - codewise-network

  indexer:
    build: ./indexer
    ports:
      - "8002:8002"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WORKSPACE_DIR=/workspace
    volumes:
      - ./workspace:/workspace
    networks:
      - codewise-network

networks:
  codewise-network:
    driver: bridge 